// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMa1lhy7i-gGCAStFELcd-3qIMgLmJB_4',
    appId: '1:842851425529:web:77f82245e6649de2bcd628',
    messagingSenderId: '842851425529',
    projectId: 'mynotes-naggita-flutter-1187b',
    authDomain: 'mynotes-naggita-flutter-1187b.firebaseapp.com',
    storageBucket: 'mynotes-naggita-flutter-1187b.firebasestorage.app',
    measurementId: 'G-KB1TB35XV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA647oP26RI71oCfPJrxHrBmDOrASnboQ',
    appId: '1:842851425529:android:87ba5799296a0683bcd628',
    messagingSenderId: '842851425529',
    projectId: 'mynotes-naggita-flutter-1187b',
    storageBucket: 'mynotes-naggita-flutter-1187b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6BQ2klq8FqXUFCWyNTQ8PzSbJmXNJr7Y',
    appId: '1:842851425529:ios:b6cf5814cd80f633bcd628',
    messagingSenderId: '842851425529',
    projectId: 'mynotes-naggita-flutter-1187b',
    storageBucket: 'mynotes-naggita-flutter-1187b.firebasestorage.app',
    iosBundleId: 'com.ethel.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6BQ2klq8FqXUFCWyNTQ8PzSbJmXNJr7Y',
    appId: '1:842851425529:ios:b6cf5814cd80f633bcd628',
    messagingSenderId: '842851425529',
    projectId: 'mynotes-naggita-flutter-1187b',
    storageBucket: 'mynotes-naggita-flutter-1187b.firebasestorage.app',
    iosBundleId: 'com.ethel.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMa1lhy7i-gGCAStFELcd-3qIMgLmJB_4',
    appId: '1:842851425529:web:7d56bd365041301fbcd628',
    messagingSenderId: '842851425529',
    projectId: 'mynotes-naggita-flutter-1187b',
    authDomain: 'mynotes-naggita-flutter-1187b.firebaseapp.com',
    storageBucket: 'mynotes-naggita-flutter-1187b.firebasestorage.app',
    measurementId: 'G-1BLFELGS3H',
  );
}
